### PR TITLE
Data visualisation

### PR DESCRIPTION
**Pull request by jadali17**
#### Reference Issues/PRs

This is to deal with the following improvement request #64 

#### What does this implement/fix? Explain your changes.

I added two plots to view the variation of the prices according to features such as garage car slot numbers and pool size.
I also added a plot that compares the predictions with the actual sales price, this one will update in real time to show us how the prediction improve over time over every 10,000 epochs.

#### Any other comments?

If i made any mistake please let me know, i am not that familiar with data visualisation so this was actually quite interesting to work with. I'll try to see what else can i contribute with!

### CODE REVIEW

**Comment by jadali17** [comment]
I am not quite familiar with Flake8 or what it does and fails, so any hints or tips to fix this one are more than welcome

**Comment by gimseng** [comment]
@jadali17 This is an odd issue, might not have anything to do with your codes, but the GitHub action. I'll take a look when I have time later in the week. Thanks for contributing !

**Comment by gimseng** [comment]
Hi @jadali17  thanks for the follow-up, I have since looked at it. It is some GitHub action thingy, don't worry about it. I'll take a look at your PR in a few days when I have time. Thanks for contributing !

**Comment by gimseng** [comment]
I apologize for the delay, in a middle of a hectic few weeks, I'll get back to this next week. Sorry and thanks for the patience !

**Comment by gimseng** [comment]
@jadali17 I finally had time to review your PR. Looks great and thanks for contributing to visualization for linear regression. I'll merge it now.

**Pull request merged**
