### PR TITLE
Health-Vehicle Insurance Cross Sell Prediction (using kNN classification)

### LINKED ISSUE #108: [EXE] Health Insurance Cross Sell Production
#### Learning Goals
Learn the concept of KNN algorithm for classification.

### Exercise Statement
This exercise helps in classifying likelihood of a person to get insurance policy for his/her vehicle based on different factors including age, gender, having health insurance etc. 

### Prerequisites 
Must know the basic statistics and a programming language and concepts of scikit-learn.

### Data source/summary:
This data is available on Kaggle, a task open for anyone interested to take up.
 
### (Optional) Suggest/Propose Solutions
I have a solution notebook for this using KNN available on my Kaggle profile and would love to share my contribution by creating a  pull request.

### (Optional) Further Links/Credits to Relevant Resources:
This task is available [here](https://www.kaggle.com/anmolkumar/health-insurance-cross-sell-prediction)

### PR DESCRIPTION
**Pull request by tanviagwl98**
#### Reference Issues/PRs

Fixes #108 . See also #111 .

#### What does this implement/fix? Explain your changes.
I proposed an exercise for ML practice and this is the solution for the same problem statement. In this KNN algorithm of classification is used. In this I have changed the name of the folder to avoid conflict for the author of the repository before merging.

#### Any other comments?
Feel free to make changes to improve performance of the model

### CODE REVIEW

**Review by AjayKhalsa — APPROVED** [review]
Hi, it looks like your project is for vehicle insurance & not health insurance, so please clarify that in your readme as it seems a little confusing & change the file name appropriately. Otherwise, it looks good.

**Comment by tanviagwl98** [comment]
> Hi, it looks like your project is for vehicle insurance & not health insurance, so please clarify that in your readme as it seems a little confusing & change the file name appropriately. Otherwise, it looks good.

**Comment by tanviagwl98** [comment]
@AjayKhalsa thank you for checking this out. I have made the changes asked by you.

**Comment by gimseng** [comment]
@tanviagwl98 I am confused. Is this the same as #111 or not? (up to name change).
If its the same, why not update there?
If its not the same, could you remind me what's the difference?

**Comment by tanviagwl98** [comment]
@gimseng Yes,  it is the same. I changed the folder name in a new branch as I was not getting to update that in the same branch. I am new to open source contribution, if you can help me that would be great.

**Comment by gimseng** [comment]
@tanviagwl98 Thanks. Is it ok for us to close #111 then and focus on this?
If so, please provide more details (maybe copy some from #111) on this PR on the codes and project.

**Comment by tanviagwl98** [comment]
@gimseng It can be closed as I have made the changes in #120 to avoid conflict

**Comment by gimseng** [comment]
@tanviagwl98 Could you clarify if this is health insurance or vehicle insurance data? I think the kaggle link also has a very confusing description on the data. We should either write more detailed and clearer description of the data or find better data.

**Comment by tanviagwl98** [comment]
@gimseng it is vehicular insurance based on person's preference having health insurance , so that is why it states cross sell prediction.

**Comment by gimseng** [comment]
@tanviagwl98 Thanks ! I see, so these clients are existing healthy insurance policy holders of this company, and they do not have vehicle insurance with the company. The goal is to predict if they are interested in subscribing to the vehicle insurance policy?

I'll clean up a few things to make that clear. Then will review the codes appropriately hopefully by the weekend. Thanks for the help !

**Comment by gimseng** [comment]
@tanviagwl98 I think the corr. matrix for vehicle age is problematic since as it stands, vehicle age=2 for all data. I think the codes you wanted for `VehicleAge` function should be:
```
def VehicleAge(age):
    if age == '< 1 Year':
        return 0
    elif age == '1-2 Year':
        return 1
    else:
        return 2
```
Please update this if you agree, then I'll merge and do a bit of clean up with links and paths.

Thanks !

**Comment by tanviagwl98** [comment]
@gimseng thanks for spotting that error, I missed that and stuck with that. I am making the change in my kaggle notebook and sharing the link of the same.

**Comment by gimseng** [comment]
@tanviagwl98 Thanks! 

Just a note on the readme, I'll revert it back to what I wrote before. The reason is since we treat each project as a collaborative project, it shouldn't refer to a particular person's kaggle / work, unless it has to do with data source. 

I'll merge, thanks for contributing !

**Comment by tanviagwl98** [comment]
@gimseng thank you for informing that. And yes thank you for providing with this opportunity to contribute. Hope to contribute in future too.

**Pull request merged**
