### PR TITLE
Added MNIST Digit Recognizer

### PR DESCRIPTION
**Pull request by aarpit1010**
jupyter notebook has been added, but still few changes are to be made in the repo like adding link to colab and nbviewer.
Sorry, I couldn't get that done.

### CODE REVIEW

**Comment by gimseng** [comment]
@aarpit1010 Thanks ! If someone else has time to review it, go ahead. Otherwise I can take a more details look after the weekend.

**Comment by aarpit1010** [comment]
I tried to add the google colab and nb viewer links in the solution/ReadMe.md file. But they don't seem to be working for some reason.

**Comment by gimseng** [comment]
Oh that's because the files haven't merge into master so the links are not pointing correctly yet. I will take care of them when we finally merge.

**Comment by gimseng** [comment]
Ref. #16.

**Comment by gimseng** [comment]
@aarpit1010 Just a comment on the git side. Typically, you fork, then git clone to your local machine. Then you create a new branch (say `my_feature`). Do work, then make sure your fork `master` is up-to-date with original repo's `master`. If there are changes, compare (in your local) between your (fork) `master` and your (fork) `my_feature`. Resolve any conflicts. Eventually, you do something like `git push -u origin my_feature` so that on your GitHub, the `my_feature` branch contains all your changes. 

Essentially, when you create a pull-request, it should be from `your-git-hub: my_feature` to `my-git-hub:master` rather than your master to my master. In this way, when I need to make changes to your PR, I won't be working on your `master`.

For now, I'll make the changes to your `master` instead, and hopefully soon we can update the submission guidelines to be more clear.

**Comment by gimseng** [comment]
@aarpit1010 I tried to rename the folder to 003 by moving the files across in GitHub, but not for all files. 

For some reason, I have write access to your master on GitHub but not using my own GitHub Desktop. Please move all files to 003 or rename your folder to 003 if that's easier (and ignore/roll back what I did).

**Comment by gimseng** [comment]
@aarpit1010 I managed to run everything without errors and everything looks good. Please change the folder name, and as far as I am concerned, its good to merge.

**Pull request closed without merging**
