### PR TITLE
Sentiment Analysis

### PR DESCRIPTION
**Pull request by tejasvi541**
**Project on Sentiment Analysis using Amazon review data.**

> Contains Data Files

> Contains Jupyter Notebook with Trained Models, but with low accuracy

### CODE REVIEW

**Comment by gimseng** [comment]
@tejasvi541 Thanks for the contribution ! I'll take a closer look in a few days, when I have more time.

A few remarks:

1. Could you restructure the folder similar to say 002 or 003 projects? I have some details in [CONTRIBUTING.md](https://github.com/gimseng/99-ML-Learning-Projects/blob/master/CONTRIBUTING.md) as well on that.

2. More importantly are the readme.md files in exercise and solution folders. Typically the exercise readme will present the problem/exercise and some learning goals. If appropriate, describe and credit the data source. For the solution, if its self-explanatory in the Jupiter notebook, then the readme.md should contain at least a few lines of summary of techniques/methods used in solution.

3. This is optionally, but generally considered best practice (maybe for future git stuff): Its probably useful to name your branch to something more "obvious"/"useful" like `sentiment-analysis` or `amazon-review` instead of just a series of numbers. I sometimes named my branch randomly and am guilty of this as well. But we should all try to make better efforts.

Overall, thanks !

gs

**Comment by gimseng** [comment]
link to #68.

**Comment by tejasvi541** [comment]
Yes Sure, I will Work on it. Thanks Btw.

**Comment by gimseng** [comment]
@tejasvi541 Thanks !

**Comment by gimseng** [comment]
New PR #75.

**Pull request closed without merging**
