### PR TITLE
Added the Ist project problem & solution

### PR DESCRIPTION
**Pull request by aarpit1010**
#7 

I have added the problem as well as the solution.
If there needs to be some changes or anything, please feel free to contact.
Any inputs would be appreciated.

### CODE REVIEW

**Comment by gimseng** [comment]
@aarpit1010  Thanks for the PR. I roughly look at it, they look great ! There are just a few things about formatting and styles which will be helpful.

First of all, I converted your exercise description file into markdown. Check out github's markdown guide, it usually looks quite nice rendered on GitHub.

Secondly, I'm going to try to see if I could put 'open in google cola' links in the solution folder's readme.md. If you have some ideas, go ahead and create readme.md or something like that to describe your solutions a little bit.

Thirdly, just a comment that its usually a good practice not to work on the master branch, but to create something like 'dev-titanic' branch, and then push/pull from there. Since we haven't written down the proper guide, we shall tentatively allow what you are doing now. For future purpose, do keep that in mind. And apologies for not having the right guide up there yet. 

I'll check this out later tomorrow to see if I could implement what I suggests above.

**Comment by aarpit1010** [comment]
Thank you for your inputs.
I'll keep these things in mind in the future and I'll try to provide the link for google colab after opening the jupyter file in google drive colab notebooks. 
I have explained some points and steps of my solution in the Jupyter notebook itself but if it still needs some work, please do tell and I'll try if possible.

**Comment by gimseng** [comment]
@aarpit1010 So I found out what I wanted to do with google colab link. It turns out that you need to put some codes in the beginning of your ipynb. Please take a look at this example  of ageron's [book] (ageron/handson-ml2/blob/master/01_the_machine_learning_landscape.ipynb)

**Comment by aarpit1010** [comment]
Sir, if this is a link for the Jupyter notebook "https://www.github.com/aarpit1010/Titanic-Dataset-Analysis/blob/master/Titanic%20Survival%20Analysis.ipynb" , then after signing up in google, we can make just one change in the URL to open the notebook in Google Colab, which is :
"https://colab.research.google.com/github/aarpit1010/Titanic-Dataset-Analysis/blob/master/Titanic%20Survival%20Analysis.ipynb"

We just have to replace "github.com/..." to "colab.research.google.com/github/..." and it will open in Google Colab (considering the person opening has a signed in account in google).

**Comment by gimseng** [comment]
@aarpit1010 Yup, that seems to be the case. I was thinking if you could have that link in your .ipynb or in your markdown description file for the solution folder, you could include the google colab links instead. Its your call, but seems like a useful link to have for learners to have a quick way to run the .ipnyb file. Thanks for doing this !

**Comment by aarpit1010** [comment]
Sir, I have added the markdown file in solution folder giving instructions to open the notebook in colab.
Please verify it and if there are no more changes to be made then let us merge the PR.

**Comment by gimseng** [comment]
@aarpit1010  Thanks so much for getting the first project in !

I cleaned up a little bit here and there. I eventually added the google colab link inside the Jupyter notebook, as I found this to be useful when I open Jupyter notebook on GitHub.

There might be more work to be done to have more documentations both on the exercise and the solution, but i think we have a good base to start. Maybe others (or both of us) later on can create issues to see how to improve upon this.

Again thanks for the submission !

**Pull request merged**
