### PR TITLE
Added project with various techniques applied to Kaggle graduate admissions data

### PR DESCRIPTION
**Pull request by vishxm**
#### What does this implement/fix? Explain your changes.
I fixed and made the necessary changes which make this PR in accordance with the other projects.

#### Any other comments?
After this PR is merged, I need to update the README.md to change the path of the hyperlink in the __Solution__ heading.

### CODE REVIEW

**Comment by gimseng** [comment]
@vishxm Could you link or refer to what other projects you have in mind?
If this is on a new project, please fill in the details of the PR template. Thanks !

**Comment by vishxm** [comment]
The changes were made on an earlier PR. Mr Khalsa suggested some changes to be made in project description. I made the necessary ones.

**Comment by gimseng** [comment]
@vishxm yes, but do link to that particular PR, even if its closed. And have a brief summary/description of what the other PR is. This helps to keep a clean history and a readable thread.

**Comment by vishxm** [comment]
My bad! Here is the link to the previous PR https://github.com/gimseng/99-ML-Learning-Projects/pull/110. The description can be found in the README of the newly added directory. Link to that is https://github.com/vishxm/99-ML-Learning-Projects/blob/vishxm-do/008/README.md

**Comment by gimseng** [comment]
@vishxm Thanks for the reply. A few questions/suggestions/comments:

1. Does this PR (and PR #110) resolve anything in the issue ticket? We prefer that you create your new project ideas based on an existing issue ticket. This allows discussions to happen, and we could provide suggestions and comments on the idea/project scope, especially on how it fits into the general goals of the repo.

2. I think your `data` and `solution` folders are flipped.

3. Please provide link to your kaggle data source in the `readme.md` in either (or both) `exercise` or `data`. Please do not have a `readme.md' in your project root folder, perhaps delegate the information to either `data`/`exercise`/`solutions`.

4. Please rename your project folder name to other placeholder name, to avoid conflicts.

5. Please describe/summarize the data either in  the `readme.md` in either (or both) `exercise` or `data`.

6. I am a little confused about this project/exercise. Is it a regression problem or a classification problem? Moreover, is it a supervised or unsupervised problem (e.g. clustering?)? Related to 1 above, this is another reason to discuss this in an issue ticket, where many people can contribute ideas/discussions. I think its ok to have an interesting dataset and perform a few types of ML techniques. But I'd like a more detailed descriptions of why different types of techniques are required.

**Pull request closed without merging**
