### PR TITLE
Contrib commands

### LINKED ISSUE #40: more details on git docs
Create a more specific fork-clone-... steps for *our* project. A step-by-step version of how to do that and contribute new exercise and/or solution will be useful to new git/github users.

### PR DESCRIPTION
**Pull request by zeina99**
#### Reference Issues/PRs

Fixes #40 

#### What does this implement/fix? Explain your changes.

Added more details to the contribution guide by adding commands and short explanations to the command

#### Any other comments?

I am not sure if this is detailed enough to how it was expected to be.
If not, please let me know and I will apply the requested changes.

### CODE REVIEW

**Comment by zeina99** [comment]
According to the error provided by github actions:
```
##[error]Version 3.6.11 with arch x64 not found
Available versions:

2.7.18 (x64)
3.5.9 (x64)
3.6.12 (x64)
3.7.9 (x64)
3.8.5 (x64)
```
I have not setup actions before.. but it seems the python version needs to be changed

**Comment by gimseng** [comment]
Hi @zeina99 thanks for the follow-up, I have since looked at it. It is some GitHub action thingy, don't worry about it. I'll take a look at your PR in a few days when I have time. Thanks for contributing !

**Comment by gimseng** [comment]
I apologize for the delay, in a middle of a hectic few weeks, I'll get back to this next week. Sorry and thanks for the patience !

**Comment by gimseng** [comment]
@zeina99 I finally had time to look at your changes. They look great ! Thanks for improving the contributing guidelines, the improvements are much needed. I'll merge now.

**Pull request merged**
