### PR TITLE
Titanic subtask

### LINKED ISSUE #71: [IMP] Adding subtasks in exercise 001
Since this repo is aimed at people trying to learn machine learning, I think it would be helpful if subtasks were added in exercise 001, especially in regards to data analysis and feature engineering.

Like for example:
- data analysis
    - plot the survival rate of males and females 
    - Survival rate based on age
    - etc..
    - finally, what observations do you make of the analysis?
- feature engineering
    - dealing with missing values
    - dealing with categorical values
    - etc..
- building the model
    - choose a model
    - fit the data
    - get the accuracy metrics
    - **bonus**: test on multiple models and compare accuracy

Since it can be a little overwhelming at the start, providing some sort of outline could be helpful.
If the above steps are too specific, it could be a little more broad to allow the person to think by themselves.

A bonus section could also be added, for those who want to go the extra mile.

### PR DESCRIPTION
**Pull request by zeina99**
#### Reference Issues/PRs

Fixes #71 

#### What does this implement/fix? Explain your changes.

Adding subtasks to exercise 001

#### Any other comments?

Thoughts on this?
are tasks too specific?

### CODE REVIEW

**Comment by aarpit1010** [comment]
This idea looks good. But do you think we should create another Jupyter notebook writing a few commands and leave the rest for them to fill up or do you want to make changes in my original solution ?

**Comment by zeina99** [comment]
Yes I also prefer creating another jupyter notebook as some sort of template which they can follow and then have them go ahead and compare it to your solution.

So my understanding is that the template would be similar to your solution in terms of the steps done. The task would be written and they would have to write some code to achieve the task, correct?

**Comment by aarpit1010** [comment]
> Yes I also prefer creating another jupyter notebook as some sort of template which they can follow and then have them go ahead and compare it to your solution.
> 
> So my understanding is that the template would be similar to your solution in terms of the steps done. The task would be written and they would have to write some code to achieve the task, correct?

Yeas, I think that's a good option.
Also, I would like you to include more plots and figures if possible as they are a bit less in the solution notebook.

**Comment by zeina99** [comment]
Alright sounds great!
I will get started on it and hopefully it will be done in a week or less

**Comment by gimseng** [comment]
@aarpit1010 and @zeina99 thanks for taking care of this. I'm glad that organic discussions and improvements are undergoing. Thanks !

**Comment by gimseng** [comment]
@zeina99 Thanks for the contribution ! I cleaned up a bit, mainly typos/capitalization and wordings, plus a few path links and stuff. Otherwise, looks great ! I'll merge now.

**Pull request merged**
