### PR TITLE
Linear regression project

### PR DESCRIPTION
**Pull request by Ar-Kareem**
Linear Regression Project.

I suggest only spending time on the 'solution' Notebook since it's basically a copy of the 'Exercise' but an implementation instead of raising a NotImplementedError.

All comments/suggestions/ideas are welcome.

### CODE REVIEW

**Comment by gimseng** [comment]
@Ar-Kareem Thanks ! I will take a look after the weekend.

For future reference, please fork it and create a new branch there. As core team, you have access to branching in this repo, but everyone else usually has to fork to their own repo to start branching.

**Comment by gimseng** [comment]
@Ar-Kareem : Thanks for the exercise/solution, looks great !

 I added various links, though most of them won't work until we merged. Importantly is the link to data source, which for now I'll just link it to data on our GitHub.

One suggestion for the overall presentation:
1. Could you add, either in one or both exercise and solution, a plot of the data before running the model, preferable after you loaded the data? It is useful to list out a few data points (in pandas, that's the head method) and/or plot the graph. In that way, the learners understand how/why we are using linear regression, instead of just blindly running the model

2. After training (20,000 epochs!), could you plot the data with the model predictions from linear regression? Optionally/bonus, if you could plot a few predictions, say one from after 1000 epochs, one from 10,000 epochs and one from 20,000 epochs. This illustrates how the fitting get better and better (if it doesn't, then we should have stopped much earlier in our training process).

Once you got 1 and 2 done, we are ready to merge. Thanks for the contribution !

**Comment by gimseng** [comment]
Once (1) an (2) suggestions above been implemented, looks good to me. Someone else should review this and feel free to merge.

**Comment by gimseng** [comment]
Reference to issue #1.

**Comment by AjayKhalsa** [comment]
Looks good I fixed some typos @gimseng.  It's really good for now I'll merge it and @Ar-Kareem can the update it later .

**Comment by gimseng** [comment]
Thanks @AjayKhalsa  and @Ar-Kareem !

**Comment by gimseng** [comment]
@AjayKhalsa Actually for future reference, please do not merge until all changes and commits are done on a branch. In this way, we have a self contained branch and a self contained PR thread. Typically, one then deletes the branch after merging. There is no rush to close the PR anyway.

**Comment by AjayKhalsa** [comment]
@gimseng oh sorry, I'll keep that in mind

**Comment by gimseng** [comment]
@ajaykhalsa np this is how we learn, also means that I should probably write up a much better and detailed Got-workflow on solution pull request.

For now, it seems like another PR has been opened up for this, perhaps we could continue the discussion there.

**Comment by gimseng** [comment]
@ar-Kareem it seems like probably least messy if you start a new PR after you add the few changes suggested. Ref back to this PR though. Thanks !

**Pull request merged**
