### PR TITLE
Added the link for housing_prices data

### PR DESCRIPTION
**Pull request by vardhanaleti**
Hey!
I've added the link to the housing_prices dataset in /exercise/readme.md file.

### CODE REVIEW

**Comment by vardhanaleti** [comment]
Hey!
I've added the link for the housing_prices dataset,

**Comment by gimseng** [comment]
Link to issue #65

**Comment by gimseng** [comment]
I just cleaned up a bit of wordings. Will merge, thanks @vardhanaleti !

**Comment by vardhanaleti** [comment]
Thank you! @gimseng :)

**Pull request merged**
