### PR TITLE
Sentiment analysis improve

### PR DESCRIPTION
**Pull request by tejasvi541**

### CODE REVIEW

**Comment by gimseng** [comment]
Hi @tejasvi541, could you explain more on what you have changed? So far, I saw a few upper-to-lower case changes and a new `ReviewContainer` object called `cont`. However I didn't see `cont` being used after cell 11.

The last line of the notebook is still "We will add one more container class above which will evenly distribute the positives and negatives in cell 8.". Again, do you intend for more codes after this, or perhaps we should rephrase the sentence a little if it wasn't meant for that.

**Comment by gimseng** [comment]
@tejasvi541 Have you had some time to take a look at this? Otherwise, I might clean up a bit and ignore the last part of the notebook.

Unfortunately I am in a middle of a hectic few weeks, I'll get back to this next week. Sorry and thanks for the patience !

**Comment by tejasvi541** [comment]
Hey @gimseng ,
Sorry for the late reply , was busy with the hectic online college classes. The code is complete from my side, as it mentioned to use the container in the last lines of the notebook, is it so because I added it after forming the model once and then segregating the data using that container in the 11th cell. So its Complete for my side, as I am just a beginner i have not that much insights with me as of now.
Thanks, and I am also looking forward to add more projects.

**Comment by gimseng** [comment]
@tejasvi541 Thanks for the reply. I spent a little more time on your code, and now I understood what you meant. Great codes and I liked how you refactored things. Will merge now, and looking forward to your other projects.

**Pull request merged**
